#remote_theme: pages-themes/cayman@v0.2.0
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-sitemap
logo: /assets/img/TaoMorisaki.jpg
title: Tao Morisaki (森崎汰雄)
description: tao.morisaki[at]ntt.com.
