#remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme
theme: jekyll-theme-minimal
logo: /assets/img/TaoMorisaki.jpg
title: Tao Morisaki
description: tao.morisaki[at]ntt.com.
